application: tracker-gae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /html
  static_dir: html
- url: /res
  static_dir: res
- url: /.*
  script: tracker-gae.app
  secure: always
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest